apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- project-persistentvolumeclaim.yaml
- project-persistentvolume.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: eerola/todo-app
  newName: eerola/todo-app
  newTag: 70f121c9a4db3b05956688e4283070685a194b2c
