apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- namespace.yaml
- project-persistentvolume.yaml
- project-persistentvolumeclaim.yaml
- ../../project/base
- ../../todo-backend/base
- ../../todo-fetcher/base
- ../../broadcaster/base

images:
- name: eerola/broadcaster
  newName: eerola/broadcaster
  newTag: b75697e1d6a0b42247ce25862d5ec676badb6262
- name: eerola/todo-app
  newName: eerola/todo-app
  newTag: b75697e1d6a0b42247ce25862d5ec676badb6262
- name: eerola/todo-backend
  newName: eerola/todo-backend
  newTag: b75697e1d6a0b42247ce25862d5ec676badb6262
- name: eerola/todo-fetcher
  newName: eerola/todo-fetcher
  newTag: b75697e1d6a0b42247ce25862d5ec676badb6262

patches:
- patch: |-
    - op: add
      path: /spec/rules/0/host
      value: staging.localhost
  target:
    kind: Ingress
    name: project-ingress
