apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: hash-file
          emptyDir: {}
      containers:
      - name: log-output-writer
        image: eerola/log-output-writer:1.10.1
        volumeMounts:
        - name: hash-file
          mountPath: /usr/src/app/files
      - name: log-output-reader
        image: eerola/log-output-reader:1.10.1
        volumeMounts:
        - name: hash-file
          mountPath: /usr/src/app/files
