apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
      - name: pingpong
        image: eerola/pingpong:3.4
        imagePullPolicy: Always
        env:
          - name: PORT
            value: "3000"
          - name: POSTGRES_HOST
            value: "postgres-stset"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgre-secrets
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgre-secrets
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgre-secrets
                key: POSTGRES_USER
