apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: hash-file
          persistentVolumeClaim:
            claimName: hash-claim
      containers:
      - name: pingpong
        image: eerola/pingpong:1.11.1
        volumeMounts:
        - name: hash-file
          mountPath: /usr/src/app/files
        imagePullPolicy: Always
        env:
          - name: PORT
            value: "3000"
