apiVersion: v1
kind: Secret
metadata:
  namespace: exercises
  name: postgre-secrets
type: Opaque
stringData:
  POSTGRES_DB: pingpong-counter-storage
  POSTGRES_PASSWORD: password
  POSTGRES_USER: admin
