apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: project
  name: postgres-stset
spec:
  serviceName: postgres-stset
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgre-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgre-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgre-secrets
                  key: POSTGRES_USER
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: project-todo-storage
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - metadata:
        name: project-todo-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
