apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - namespace.yaml
  - project-persistentvolume.yaml
  - project-persistentvolumeclaim.yaml
  - ../../project/base
  - ../../todo-backend/base
  - ../../todo-fetcher/base
  - ../../broadcaster/base
  - ../../database-backup/base

images:
  - name: eerola/todo-app
    newName: eerola/todo-app
    newTag: "4.5.1"
  - name: eerola/todo-backend
    newName: eerola/todo-backend
    newTag: "4.5.1"
  - name: eerola/todo-fetcher
    newName: eerola/todo-fetcher
    newTag: "3.5"
  - name: eerola/broadcaster
    newName: eerola/broadcaster
    newTag: "4.6.2"

patches:
  - target:
      kind: Deployment
      name: broadcaster
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: DISCORD_WEBHOOK_URL
            valueFrom:
              secretKeyRef:
                name: discord-webhook
                key: DISCORD_WEBHOOK_URL

  - target:
      kind: Ingress
      name: project-ingress
    patch: |-
      - op: add
        path: /spec/rules/0/host
        value: production.localhost