apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-claim
spec:
  storageClassName: project-pv-production
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi