apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- statefulset.yaml
- secret.yaml
- postgres-service.yaml
images:
- name: eerola/todo-backend
  newName: eerola/todo-backend
  newTag: 70f121c9a4db3b05956688e4283070685a194b2c
