name: Release application

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-publish-release:
    name: Build, publish and release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish project
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag eerola/todo-app:$GITHUB_SHA \
            --push \
            ./project

      - name: Build and publish todo-backend
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag eerola/todo-backend:$GITHUB_SHA \
            --push \
            ./todo-backend

      - name: Build and publish todo-fetcher
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag eerola/todo-fetcher:$GITHUB_SHA \
            --push \
            ./todo-fetcher

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v3

      - name: Update images
        run: |
          cd project/base
          kustomize edit set image eerola/todo-app=eerola/todo-app:$GITHUB_SHA

          cd ../../todo-backend/base
          kustomize edit set image eerola/todo-backend=eerola/todo-backend:$GITHUB_SHA

          cd ../../todo-fetcher/base
          kustomize edit set image eerola/todo-fetcher=eerola/todo-fetcher:$GITHUB_SHA

      - name: Commit updated Kustomize files
        uses: EndBug/add-and-commit@v10
        with:
          add: |
            project/base/kustomization.yaml
            todo-backend/base/kustomization.yaml
            todo-fetcher/base/kustomization.yaml
          message: "Release ${{ github.sha }}"
