name: Release application

on:
  push:
    branches:
      - main
    tags:
      - "**"
    paths-ignore:
      - "**/*.md"
      - "environments/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-publish-release:
    name: Build, publish and release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and publish project
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag eerola/todo-app:$GITHUB_SHA \
            --push \
            ./project

      - name: Build and publish todo-backend
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag eerola/todo-backend:$GITHUB_SHA \
            --push \
            ./todo-backend

      - name: Build and publish todo-fetcher
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag eerola/todo-fetcher:$GITHUB_SHA \
            --push \
            ./todo-fetcher

      - name: Build and publish broadcaster
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag eerola/broadcaster:$GITHUB_SHA \
            --push \
            ./broadcaster

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v3

      - name: Update staging images
        if: github.ref == 'refs/heads/main'
        run: |
          cd environments/staging
          kustomize edit set image \
            eerola/todo-app=eerola/todo-app:$GITHUB_SHA \
            eerola/todo-backend=eerola/todo-backend:$GITHUB_SHA \
            eerola/todo-fetcher=eerola/todo-fetcher:$GITHUB_SHA \
            eerola/broadcaster=eerola/broadcaster:$GITHUB_SHA

      - name: Update production images
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd environments/production
          kustomize edit set image \
            eerola/todo-app=eerola/todo-app:$GITHUB_SHA \
            eerola/todo-backend=eerola/todo-backend:$GITHUB_SHA \
            eerola/todo-fetcher=eerola/todo-fetcher:$GITHUB_SHA \
            eerola/broadcaster=eerola/broadcaster:$GITHUB_SHA

      - name: Commit updated Kustomize files
        uses: EndBug/add-and-commit@v10
        with:
          add: |
            environments/staging/kustomization.yaml
            environments/production/kustomization.yaml
          message: "Release ${{ github.sha }} [skip ci]"